### ISSUE TITLE
Update forta-agent package version

### ISSUE THREAD

**Issue by haseebrabbani** [arbitraryexecution/forta-agent-templates#18]
A major release of the `forta-agent` package was just published (v0.1.1). The templates should migrate to this version as soon as possible. Code changes would only be required if the template is using the `receipt`, `status` or `gasUsed` properties of the `TransactionEvent` object (otherwise its just a version bump). see this Discord message for more details: https://discord.com/channels/869983523371642921/869986794970693723/959487384767070348

**Comment by echoAE** [comment]
Addressed by: https://github.com/arbitraryexecution/forta-agent-templates/pull/19
